name: meditrack_flutter
description: A comprehensive medication tracking and management app built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^16.2.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # GraphQL Client
  graphql_flutter: ^5.1.2
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Camera & Image Processing
  camera: ^0.11.2
  image_picker: ^1.0.4
  
  # OCR
  google_mlkit_text_recognition: ^0.15.0
  
  # Speech Recognition
  speech_to_text: ^7.3.0
  
  # Notifications
  flutter_local_notifications: ^19.4.0
  
  # UI Components
  flutter_svg: ^2.0.9
  table_calendar: ^3.0.9
  
  # Utilities
  http: ^1.1.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600